on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: deploy to dockerhub
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: fbust
          password: dckr_pat_E6KPEgEr7H82hfzpneET_dzl_ak
          
      - name: Construye Imagen
        run: |
          echo "Building Docker image..."
          docker build -t fbust/hola-mundo:${{ github.run_number }} .
      - name: Pushea Imagen
        run: |
          echo "Pushing Docker image..."
          docker push fbust/hola-mundo:${{ github.run_number }}
